-- MySQL Script generated by MySQL Workbench
-- Wed Feb 16 17:59:40 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema certlibrary
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema certlibrary
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `certlibrary` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `certlibrary` ;

-- -----------------------------------------------------
-- Table `certlibrary`.`course`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `certlibrary`.`course` (
  `course_id` INT NOT NULL AUTO_INCREMENT,
  `course_tittle` VARCHAR(256) CHARACTER SET 'utf8' NOT NULL,
  `platform` VARCHAR(256) CHARACTER SET 'utf8' NOT NULL,
  `category` VARCHAR(256) NOT NULL,
  PRIMARY KEY (`course_id`),
  UNIQUE INDEX `course_id_UNIQUE` (`course_id` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 12
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `certlibrary`.`course_detail`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `certlibrary`.`course_detail` (
  `course_detail_id` INT NOT NULL AUTO_INCREMENT,
  `image` VARCHAR(500) NULL DEFAULT NULL,
  `course_id` INT NOT NULL,
  `course_length` FLOAT NULL DEFAULT NULL,
  PRIMARY KEY (`course_detail_id`),
  UNIQUE INDEX `course_detail_id_UNIQUE` (`course_detail_id` ASC) VISIBLE,
  UNIQUE INDEX `course_id_UNIQUE` (`course_id` ASC) VISIBLE,
  CONSTRAINT `couse_id`
    FOREIGN KEY (`course_id`)
    REFERENCES `certlibrary`.`course` (`course_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 12
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `certlibrary`.`employee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `certlibrary`.`employee` (
  `employee_id` INT NOT NULL AUTO_INCREMENT,
  `full_name` VARCHAR(45) CHARACTER SET 'utf8' NOT NULL,
  `user_name` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NULL DEFAULT NULL,
  `profile_image` VARCHAR(500) NULL DEFAULT NULL,
  PRIMARY KEY (`employee_id`),
  UNIQUE INDEX `employee_id_UNIQUE` (`employee_id` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  UNIQUE INDEX `profile_image_UNIQUE` (`profile_image` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 20
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `certlibrary`.`course_employee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `certlibrary`.`course_employee` (
  `course_id` INT NOT NULL,
  `employee_id` INT NOT NULL,
  `status` INT NOT NULL,
  `start_date` DATETIME NOT NULL,
  `end_date` DATETIME NULL DEFAULT NULL,
  `cert_link` VARCHAR(256) NULL DEFAULT NULL,
  `isDeleted` TINYINT(1) NULL DEFAULT NULL,
  PRIMARY KEY (`course_id`, `employee_id`),
  INDEX `employee_id_idx` (`employee_id` ASC) VISIBLE,
  CONSTRAINT `course_id`
    FOREIGN KEY (`course_id`)
    REFERENCES `certlibrary`.`course` (`course_id`),
  CONSTRAINT `employee_id`
    FOREIGN KEY (`employee_id`)
    REFERENCES `certlibrary`.`employee` (`employee_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `certlibrary`.`course_skills`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `certlibrary`.`course_skills` (
  `c_skill_id` INT NOT NULL AUTO_INCREMENT,
  `skill_name` VARCHAR(45) CHARACTER SET 'utf8' NOT NULL,
  `course_id` INT NOT NULL,
  PRIMARY KEY (`c_skill_id`, `course_id`),
  INDEX `course_id_idx` (`course_id` ASC) VISIBLE,
  CONSTRAINT `course_skills_ibfk_1`
    FOREIGN KEY (`course_id`)
    REFERENCES `certlibrary`.`course` (`course_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 26
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `certlibrary`.`employee_skills`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `certlibrary`.`employee_skills` (
  `e_skill_id` INT NOT NULL AUTO_INCREMENT,
  `skill_name` VARCHAR(45) CHARACTER SET 'utf8' NOT NULL,
  `employee_id` INT NOT NULL,
  PRIMARY KEY (`e_skill_id`),
  UNIQUE INDEX `e_skill_id_UNIQUE` (`e_skill_id` ASC) VISIBLE,
  INDEX `employee_id_idx` (`employee_id` ASC) VISIBLE,
  CONSTRAINT `employee_skills_ibfk_1`
    FOREIGN KEY (`employee_id`)
    REFERENCES `certlibrary`.`employee` (`employee_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 28
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
